name: blog_note_android
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2        # ← movido aquí
  sqflite: ^2.3.3         # ← movido aquí
  path: ^1.9.0            # ← movido aquí
  intl: ^0.19.0           # ← movido aquí
  flutter_speed_dial: ^7.0.0
  share_plus: ^10.0.0

dependency_overrides:      # ← fuera de dev_dependencies
  sqflite_android: ^2.3.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  assets:
    - assets/icon/
  uses-material-design: true